version: '3'

services:
  broker:
    image: eclipse-mosquitto
    volumes:
    - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"

  publisher:
    build: ./services/publisher
    depends_on:
      - broker

  subscriber:
    build: ./services/subscriber
    depends_on:
      - broker

  api:
    build: ./services/api
    ports:
      - "5000:5000"